/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package playground;
import main.java.playground.LRUCache;

public class App {
    public String getGreeting() {
        return "Hello Ramya!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        LRUCache cache = new LRUCache(2);
        System.out.println(cache.get(4));
        cache.put(4,10);
        System.out.println("Adding key 4, value 10");
        System.out.println(cache.get(4));
        System.out.println(cache.get(7));
        cache.put(7,20);
        System.out.println("Adding key 7 value 20");
        System.out.println(cache.get(7));
        System.out.println(cache.get(9));
        cache.put(9,30);
        System.out.println("Adding key 9 value 30");
        System.out.println(cache.get(4));
        System.out.println(cache.get(7));
        System.out.println(cache.get(9));
    }
}
